// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using smarthack.Data;

namespace smarthack.Migrations
{
    [DbContext(typeof(SmartHackDbContext))]
    partial class SmartHackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("smarthack.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Increase");

                    b.Property<string>("Name");

                    b.Property<double>("Percent");

                    b.Property<double>("Price");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("smarthack.Models.News", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CompanyId");

                    b.Property<string>("Content");

                    b.Property<string>("Headline");

                    b.Property<string>("Link");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Newses");
                });

            modelBuilder.Entity("smarthack.Models.News", b =>
                {
                    b.HasOne("smarthack.Models.Company", "Company")
                        .WithMany("Newses")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
